
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vtt3d = { path = "../game", default-features = false }

[features]
default = ["vtt3d/default"]
dylib-engine = ["vtt3d/dylib-engine"]
